Controllers/CartController.cs
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using HalalDelivery.Logic;
using HalalDelivery.Models;

namespace HalalDelivery.Controllers
{
    public class CartController : Controller
    {
        private readonly ShoppingCartActions _actions;

        public CartController(ShoppingCartActions actions)
        {
            _actions = actions;
        }

        public IActionResult AddToCart(int id, string url)
        {
            _actions.AddToCart(id);
            
            return Redirect(url);
        }

        public IActionResult Cart()
        {
            return View(_actions.GetCartItems());
        }

        public IActionResult IncreaseQuantity(int id, string url)
        {
            _actions.ChangeQuantity(id,1);
            return Redirect(url);
        }
        public IActionResult DecreaseQuantity(int id, string url)
        {
            _actions.ChangeQuantity(id,-1);
            return Redirect(url);
        }

        public IActionResult Remove(int id, string url)
        {
            _actions.RemoveFromCart(id);
            return Redirect(url);
        }

        public IActionResult RemoveAll(string url)
        {
            _actions.RemoveAllPositions();
            return Redirect(url);
        }

        public IActionResult PreOrder()
        {
            return View(_actions.GetCartItems());
        }

        public IActionResult MakeOrder()
        {
            _actions.MakeOrder();
            _actions.RemoveAllPositions();
            return View();
        }
    }
}

Controllers/CatalogController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using HalalDelivery.Data;
using HalalDelivery.Models;

namespace HalalDeliverylivery.Controllers
{
    public class CatalogController : Controller
    {
        private readonly HalalDeliveryDbContext _context;
        
        public CatalogController(HalalDeliveryDbContext dbContext)
        {
            _context = dbContext;
        }

        public IActionResult AllProducts()
        {
            var catalog = new AllProductsModel
            {
                Halals = _context.Halals.ToList(), AdditionalProducts = _context.AdditionalProducts.ToList()
            };

            return View(catalog);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Halal</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head> 

<body>
<header class="p-2 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none docs-creator">
                <img src="../icons/sheep.svg" class="bi me-2" width="50" height="44" role="img" aria-label="Bootstrap" alt="Halal">
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <a style="color:#ffffff; text-decoration:none;" asp-controller="Home" asp-action="Index" class="nav-link px-2 text-white docs-creator">Главная</a>
                <a style="color:#ffffff; text-decoration:none; margin-left: 20px;" asp-controller="Catalog" asp-action="AllProducts" class="nav-link px-2 text-white docs-creator">Каталог</a>
            </ul>
           
            
            <div class="text-end">
                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <a style="color:#ffffff; text-decoration:none; margin-right: 30px;" asp-controller="Cart" asp-action="Cart">Корзина </a>
                        <a style="color:#ffffff; text-decoration:none; margin-right: 30px;" asp-controller="Account" asp-action="Account">Профиль</a>
                        <a asp-controller="Account" asp-action="Logout"><button type="button" class="btn btn-outline-light me-2">Выйти</button></a>
                    }
                    else
                    {
                        <a asp-controller="Account" asp-action="Login"><button type="button" class="btn btn-outline-light me-2">Войти</button></a>
                        <a asp-controller="Account" asp-action="Register"><button type="button" class="btn btn-warning">Зарегистрироваться</button></a> 
                    }
                }
            </div>
        </div>
    </div>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container" style="color:black">
        &copy; Halal INC
    </div>

</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>