Controllers/AdditionalProductController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using HalalDelivery.Data;

namespace HalalDelivery.Controllers
{
    public class AdditionalProductController : Controller
    {
        private readonly HalalDeliveryDbContext _context;

        public AdditionalProductController(HalalDeliveryDbContext context)
        {
            _context = context;
        }

        [Route("AdditionalProduct/{id:int}")]
        public IActionResult Index(int id)
        {
            var product = _context.AdditionalProducts.FirstOrDefault(x => x.Id == id);
            
            return View(product);
        }
    }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using HalalDelivery.Logic;
using HalalDelivery.Models;

namespace HalalDelivery.Controllers
{
    public class CartController : Controller
    {
        private readonly ShoppingCartActions _actions;

        public CartController(ShoppingCartActions actions)
        {
            _actions = actions;
        }

        public IActionResult AddToCart(int id, string url)
        {
            _actions.AddToCart(id);
            
            return Redirect(url);
        }

        public IActionResult Cart()
        {
            return View(_actions.GetCartItems());
        }

        public IActionResult IncreaseQuantity(int id, string url)
        {
            _actions.ChangeQuantity(id,1);
            return Redirect(url);
        }
        public IActionResult DecreaseQuantity(int id, string url)
        {
            _actions.ChangeQuantity(id,-1);
            return Redirect(url);
        }

        public IActionResult Remove(int id, string url)
        {
            _actions.RemoveFromCart(id);
            return Redirect(url);
        }

        public IActionResult RemoveAll(string url)
        {
            _actions.RemoveAllPositions();
            return Redirect(url);
        }

        public IActionResult PreOrder()
        {
            return View(_actions.GetCartItems());
        }

        public IActionResult MakeOrder()
        {
            _actions.MakeOrder();
            _actions.RemoveAllPositions();
            return View();
        }
    }
}

Controllers/CatalogController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using HalalDelivery.Data;
using HalalDelivery.Models;

namespace HalalDeliverylivery.Controllers
{
    public class CatalogController : Controller
    {
        private readonly HalalDeliveryDbContext _context;
        
        public CatalogController(HalalDeliveryDbContext dbContext)
        {
            _context = dbContext;
        }

        public IActionResult AllProducts()
        {
            var catalog = new AllProductsModel
            {
                Halals = _context.Halals.ToList(), AdditionalProducts = _context.AdditionalProducts.ToList()
            };

            return View(catalog);
        }
    }
}

Controllers/HalalController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using HalalDelivery.Data;

namespace HalalDelivery.Controllers
{
    public class HalalController : Controller
    {
        private readonly HalalDeliveryDbContext _context;
        
        public HalalController(HalalDeliveryDbContext context)
        {
            _context = context;
        }
        
        [Route("Halal/{id:int}")]
        public IActionResult Index(int id)
        {
            var Halal = _context.Halals.FirstOrDefault(x => x.Id == id);

            return View(Halal);
        }
    }
}

Views/Catalog/AllProducts.cshtml
@using Microsoft.AspNetCore.Http.Extensions
@model HalalDelivery.Models.AllProductsModel

@{
    ViewBag.Title = "Каталог";
    Layout = "_Layout";
}
<br>
<h2>Халяль - продукция</h2>
<br>
<div class="container">
    <div class="row g-2">
        @{
            foreach (var Halal in Model.Halals)
            {
                <div style="border: 1px solid #e2a100; padding: 10px;" class="d-flex position-relative">
                    <img src="../imgss/@{@Halal.Id}.jpeg" width="150" height="150" alt="...">
                    <div>
                        <a style="color:black; position: relative; left: 10px" asp-controller="Halal" asp-action="Index" asp-route-id="@Halal.Id">@Halal.Name</a>
                        <p style="color: #232020; position: relative; left: 10px">@Halal.Description</p>
                        <div style="position:absolute; bottom:10px;">
                            <h4 style="position: relative; left: 10px;"><span class="badge rounded-pill bg-warning text-dark">@Halal.Cost $</span></h4>
                            <a style="position: relative; left: 10px;" asp-controller="Cart" asp-action="AddToCart" asp-route-id="@Halal.Id" asp-route-url="@Context.Request.GetEncodedUrl()">
                                <button type="button" class="btn btn-warning">В корзину</button>
                            </a>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>
<br>

<br>
<h2>Дополнительные товары</h2>
<br>
<div class="container">
<div class="row g-2">
    @{
        foreach (var product in Model.AdditionalProducts)
        {
            <div style="border: 1px solid #e2a100; padding: 10px;" class="d-flex position-relative">
                <img src="../imgss/@{@product.Id}.jpeg" width="150" height="150" alt="...">
                <div>
                    <a style="color:black; position: relative; left: 10px" asp-controller="AdditionalProduct" asp-action="Index" asp-route-id="@product.Id">@product.Name</a>
                    <div style="position:absolute; bottom:10px;">
                        <h4 style="position: relative; left: 10px;"><span class="badge rounded-pill bg-warning text-dark">@product.Cost $</span></h4>
                        <a style="position: relative; left: 10px" asp-controller="Cart" asp-action="AddToCart" asp-route-id="@product.Id" asp-route-url="@Context.Request.GetEncodedUrl()">
                            <button type="button" class="btn btn-warning">В корзину</button>
                        </a>
                    </div>
                </div>
            </div>
        }
    }
</div>
</div>